### ISSUE TITLE
Source of ideas for Trading-View-IBKR

### ISSUE THREAD

**Issue by positive-expectancy** [Brandon168/Trading-View-IBKR#1]
Hi Brandon,

I didn't know any other way to contact you than via GitHub issues.  

Re: your README comments for Trading-View-IBKR, I recommend you have a look at https://www.youtube.com/results?search_query=part+time+larry.  I know there can be a lot of crap on YT, but I think this guy is really good.  

He has some code for integrating TV and IB via webhooks.  His GitHub account is hackingthemarkets and has a lot of good code.

Hope this helps.  Obviously close/delete this issue once you've read it.

**Comment by Brandon168** [comment]
Thanks @positive-expectancy! My code actually started from hackingthemarkets and evolved from there.  Larry is great!
